### ISSUE TITLE
Applying the plugin produces error by default

### ISSUE THREAD

**Issue by ieugen** [vanniktech/gradle-code-quality-tools-plugin#122]
Hi, 

Applying the plugin produces an error by default because some dependencies are missing. 
I think this is a bad user experience.
In my case I'm not building an android app so IMO the plugin should work. 
Why should it fail because it wants to build android or kotlin and I'm not using either. 
Less (automation or defaults) is more :) .

Thanks, 

````
plugins {
   ....
    id "com.vanniktech.code.quality.tools" version "0.9.0"
}
````

````
Could not find com.android.tools.build:gradle:3.0.1.
Searched in the following locations:
    https://plugins.gradle.org/m2/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom
    https://plugins.gradle.org/m2/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.jar
Required by:
    project :core > com.vanniktech.code.quality.tools:com.vanniktech.code.quality.tools.gradle.plugin:0.9.0 > gradle.plugin.com.vanniktech:gradle-code-quality-tools-plugin:0.9.0

````

**Comment by vanniktech** [comment]
You need to add the `google()` repository url. Created a PR to fix the README - https://github.com/vanniktech/gradle-code-quality-tools-plugin/pull/123
