### ISSUE TITLE
Add Lint Plugin to non android plugins via opt-in

### ISSUE THREAD

**Issue by vanniktech** [vanniktech/gradle-code-quality-tools-plugin#142]

**Comment by molexx** [comment]
Should this be applied to 0.14-SNAPSHOT?

I've tried

    classpath "com.vanniktech:gradle-code-quality-tools-plugin:0.14.0-SNAPSHOT"

and also, to be sure I'm getting the latest,  

    classpath "com.vanniktech:gradle-code-quality-tools-plugin:0.14.0-20180926.150653-5"

and I've disabled lint in the config:

    lint {
        boolean enabled = false
    }

but I'm still getting `NoClassDefFoundError: com/android/build/gradle/LintPlugin` in the evaluation phase.

**Comment by vanniktech** [comment]
Yeah I've also seen this somewhere. You get this if the Android plugin isn't on the classpath - I believe. 
Feel free to submit a pr with a fix.
