### ISSUE TITLE
[FEATURE]Has "spotlessApply" of diffplug/spotless  for  ktlint been integrated? 

### ISSUE THREAD

**Issue by XinyueZ** [vanniktech/gradle-code-quality-tools-plugin#150]
I have tried to use this plugin to ease including "ktlint", however, the command `./gradlew spotlessApply` would not be found.
Is diffplug/spotless  integrated?

**Comment by vanniktech** [comment]
Since it's not listed in the README no it hasn't. Why would you want it? ktlint already does the formatting which can be executed via `./gradlew ktlint` or `./gradlew ktlintFormat`

**Comment by vanniktech** [comment]
Sure feel free to add spotless support here as long as you comply with the current style, configuration and add proper tests.

I won't add it since I'm not using it.

**Comment by vanniktech** [comment]
Since there hasn't been any progress on this - I'll close this one.
