### ISSUE TITLE
CPD supports Kotlin with PMD version 6.10.0

### ISSUE THREAD

**Issue by vanniktech** [vanniktech/gradle-code-quality-tools-plugin#167]
https://github.com/pmd/pmd/issues/419

**Comment by Zhuinden** [comment]
Apparently the trick is that you're reusing "language" as the file extension, so CPD language has to be `kt` for the CPD checks to run.

**Comment by vanniktech** [comment]
Yes.

**Comment by vanniktech** [comment]
I just haven't had time to set it up. Also the plugin needs to be applied since it's currently only applied for Java.

**Comment by Zhuinden** [comment]
We managed to get it run with the following configuration:

```
    pmd {
        enabled = true
        toolVersion = "6.11.0"
        ruleSetFile = "code_quality_tools/pmd.xml"
        ignoreFailures = null
        source = "src"
        include = listOf("**/*.kt")
        exclude = listOf("**/gen/**")
    }
```

**Comment by vanniktech** [comment]
Yeah. I just haven't had time to include it.

**Comment by Zhuinden** [comment]
I don't know what you mean. It already works. The only thing missing is the ability to run it for both Java and Kotlin, instead of just one :D

**Comment by vanniktech** [comment]
To include it in this plugin.

**Comment by vanniktech** [comment]
I've decided to not include this.
