### ISSUE TITLE
RC13 support Detekt failFast

### ISSUE THREAD

**Issue by vanniktech** [vanniktech/gradle-code-quality-tools-plugin#173]
https://github.com/arturbosch/detekt/pull/1417/files

**Comment by arturbosch** [comment]
So your use case is to have everything inside the config file so you do not need to supports additional flags in your gradle plugin ? Hmm, thats a good use case.

**Comment by vanniktech** [comment]
Well either make things like this configurable in the CLI or in the YML file but not in both. This only leads to confusion.

We're super inconsistent. `failFast` is no longer applicable via the YML file. However, I can configure reports with the YML file which should not be possible if we are consistent. The same applies for processors, `autoCorrect` and a few other attributes.

**Comment by mikezx6r** [comment]
I think having all configuration in the yml file is the most consistent. Makes it easier to share a config across a team and ensure everyone's using the same configuration and it doesn't matter what tool I use to run it. Also simplifies determining what config was used without having to determine what flags may or may not have been passed.

I'll get the same result if I run from CLI, Gradle plugin or if there is one, Maven plugin. Common, shared configuration across the team and in the IDE plugin.

**Comment by vanniktech** [comment]
Let's wait what they say in https://github.com/arturbosch/detekt/issues/1528
