### ISSUE TITLE
Migrate from findbugs to spotbugs

### ISSUE THREAD

**Issue by Hydragyrum** [vanniktech/gradle-code-quality-tools-plugin#178]
With gradle officially deprecating the findbugs plugin (to be removed in v6, See: https://docs.gradle.org/current/userguide/findbugs_plugin.html), the code quality tools should migrate to spotbugs instead (https://plugins.gradle.org/plugin/com.github.spotbugs)

**Comment by vanniktech** [comment]
That makes sense @Hydragyrum 

Want to take a stab at it? Being honest, I haven't used findbugs in months and it's likely I'll just drop it once Gradle 6.0 is out

**Comment by Hydragyrum** [comment]
@vanniktech Stab taken with #179.

**Comment by vanniktech** [comment]
Removed Findbugs via #185 and I'll close this issue. I'll keep your PR open.
