### ISSUE TITLE
Readme.md contains dead link to groovy javadoc +.idea folder for config xml's?

### ISSUE THREAD

**Issue by GerritDeMeulder** [vanniktech/gradle-code-quality-tools-plugin#181]
It's a small issue, but for beginners incomplete documentation may be confusing :
In the readme.md file, at chapter
https://github.com/vanniktech/gradle-code-quality-tools-plugin#configuration
contains following dead link : [src/main/groovy/com/vanniktech/code/quality/tools/CodeQualityToolsPluginExtension.groovy](url)

If I understand correctly, 
`apply plugin: "com.vanniktech.code.quality.tools"`
and  the config block just go in the main project's `build.gradle `?

Also maybe some more explanation needed:
 In android studio, the specific tool (findbugs etc) XML config files are usually under the `.idea` folder,
Does this plugin need to have it's own set under `code_quality_tools` folder, 
because this folder is empty, except for `detekt.yml` ?

**Comment by vanniktech** [comment]
Oh yes. That file is now a Kotlin file. Mind creating a PR for that?

> `apply plugin: "com.vanniktech.code.quality.tools"`
> and the config block just go in the main project's `build.gradle `?

Yeah

> Does this plugin need to have it's own set under `code_quality_tools` folder,

That's the default one which you can change

**Comment by GerritDeMeulder** [comment]
> 
> 
> Oh yes. That file is now a Kotlin file. Mind creating a PR for that?
> 
I can, as soon as I am sure that what I'm doing works correctly.
But at the moment I'm not able yet to switch over my gradle configuration (separate *.gradle files and tasks for PMD, Findbugs, checkstyle and cpd plugins) to this gradle-code-quality-tools-plugin.
Even though I disable cpd in the Kotlin config file, it keeps crashing on it.
Maybe I'll better make a separate issue for that first?
