### ISSUE TITLE
checkstyle FAILED: Unable to create Root Module

### ISSUE THREAD

**Issue by gengjiawen** [vanniktech/gradle-code-quality-tools-plugin#190]
```console
> Task :ReactAndroid:checkstyle FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ReactAndroid:checkstyle'.
> Unable to create Root Module: config {/Users/daniel/code/react-native/code_quality_tools/checkstyle.xml}, classpath {null}.
```

**Comment by vanniktech** [comment]
Yeah you're missing the checkstyle configuration file.

**Comment by gengjiawen** [comment]
Is it possible to create a task to download the `code_quality_tools` ?

**Comment by vanniktech** [comment]
Just copy paste from the default configuration of the dedicated tool.

**Comment by gengjiawen** [comment]
> Just copy paste from the default configuration of the dedicated tool.

A little cumbersome IMHO.

**Comment by leo-def** [comment]
I got the same error but this file existis and the path is correct
