### ISSUE TITLE
Could not create task of type 'Cpd'

### ISSUE THREAD

**Issue by neutze** [vanniktech/gradle-code-quality-tools-plugin#203]
Hey, I ran into an issue with cpd. It cannot create the cpd task and thus doesn't run when cpd isn't disabled. Is there a way to fix it?

Plugin version 0.19.0
Android plugin is '3.6.1'
Gradle is '6.2.2'

```
> Failed to apply plugin [class 'de.aaschmid.gradle.plugins.cpd.CpdPlugin']
   > Could not create task ':testlab:cpdCheck'.
      > Could not create task of type 'Cpd'.
         > Could not create an instance of type de.aaschmid.gradle.plugins.cpd.internal.CpdReportsImpl.
            > org.gradle.api.reporting.internal.TaskReportContainer.<init>(Ljava/lang/Class;Lorg/gradle/api/Task;)V
```
My build.gradle

```
...

apply plugin: "com.vanniktech.code.quality.tools"

...

subprojects {
    codeQualityTools {
        failEarly = true
        htmlReports = true

        checkstyle {
            toolVersion = '8.30'
        }
        cpd {
            enabled = false
        }
        detekt {
            toolVersion = '1.6.0'
            config = "$rootProject.projectDir/.codequality/detekt.yml"
        }
        errorProne {
            toolVersion = '2.3.2'

        }
        kotlin {
            allWarningsAsErrors = true
        }
        ktlint {
            toolVersion = '0.36.0'
        }
        lint {
            abortOnError = true
            checkAllWarnings = true
            checkReleaseBuilds = false
            warningsAsErrors = true
        }
        pmd {
            toolVersion = '6.21.0'
        }
    }
}
```

Thank's in advance. Keep up the great work.

**Comment by vanniktech** [comment]
I've also seen this locally. Maybe the CPD version got bumped with a Gradle update and it introduced some incompatible changes?

**Comment by keciciler** [comment]
Any news on this issue? The plugin is currently unusable

**Comment by vanniktech** [comment]
Haven't had time to take a look. Do you want to?

**Comment by keciciler** [comment]
I have a look into this issue, seems like CpdReportsImpl has broken the build with this change on gradle, https://github.com/gradle/gradle/commit/35f82562f772d1da9ef9344adbdcf70ee0e85ed4

New CPD Plugin Release has fixed this constructor issue,
https://github.com/aaschmid/gradle-cpd-plugin/releases/tag/v3.1

Current CPD Plugin version is 1.2

**Comment by keciciler** [comment]
Until plugin got updated you can manually add updated CPD Plugin to your build script.
classpath 'de.aaschmid:gradle-cpd-plugin:3.1'

**Comment by vanniktech** [comment]
Thanks! Mind creating a PR that updates CPD here?

**Comment by neutze** [comment]
@keciciler thanks a lot for the manual fix
