### ISSUE TITLE
Why the docs are not showing ?

### ISSUE THREAD

**Issue by theapache64** [vanniktech/gradle-code-quality-tools-plugin#205]
I can see that you've added some docs to the ext variable.

https://github.com/vanniktech/gradle-code-quality-tools-plugin/blob/013fbb489ec3d190d94403816443ca0877672e70/src/main/kotlin/com/vanniktech/code/quality/tools/CodeQualityToolsPluginExtension.kt#L11-L14

but when I request for the docs from IDE, it's not showing

![image](https://user-images.githubusercontent.com/9678279/82753865-daf8d180-9de6-11ea-8425-f82abd18aaba.png)

Actually am trying to build a plugin. I am having similar issue. Do you know how to fix it?

https://stackoverflow.com/questions/61985548/how-to-add-docs-to-gradle-plugin-extension-variables

**Comment by vanniktech** [comment]
Nope. Sorry.
