### ISSUE TITLE
kotlin language can not be set

### ISSUE THREAD

**Issue by ventura8** [vanniktech/gradle-code-quality-tools-plugin#206]
kotlin language ( cpd { language = 'kotlin' } ) can not be set because kotlin files have .kt extension and the plugin sets .kotlin
https://github.com/vanniktech/gradle-code-quality-tools-plugin/blob/master/src/main/kotlin/com/vanniktech/code/quality/tools/CodeQualityToolsPlugin.kt#L296

**Comment by vanniktech** [comment]
language = 'kt'
