### ISSUE TITLE
Unable to create Root Module: config {/Users/ucb/Android/Projects/upay-dso/app/code_quality_tools/checkstyle.xml}, classpath {null}.

### ISSUE THREAD

**Issue by RimonGazi** [vanniktech/gradle-code-quality-tools-plugin#207]

**Comment by vanniktech** [comment]
Yeah that file can't be found. Could be because you're executing that task from a subdirectory.

**Comment by RimonGazi** [comment]
> Yeah that file can't be found. Could be because you're executing that task from a subdirectory.

Can you please  share any examples project or demo?
