### ISSUE TITLE
Old tool dependencies

### ISSUE THREAD

**Issue by quittle** [vanniktech/gradle-code-quality-tools-plugin#208]
First of all, thank you so much for building this plugin, I really appreciate not having to do much to configure my project for a bunch of static analysis tooling.

The plugin dependencies that this tool provides are getting old at this point. Would it be possible for you to upgrade the dependencies and publish a new release?

**Comment by vanniktech** [comment]
I don't see any reason why. You can configure externally used tools to use new versions.
