### ISSUE TITLE
i have make reports false global，but still gen report when i use gradle command in idea right

### ISSUE THREAD

**Issue by zcg** [vanniktech/gradle-code-quality-tools-plugin#209]
![Snipaste_2021-02-28_20-53-38](https://user-images.githubusercontent.com/68289686/109419173-1783da00-79c4-11eb-9085-8fc06b24779b.png)
![Snipaste_2021-02-28_20-53-50](https://user-images.githubusercontent.com/68289686/109419175-194d9d80-79c4-11eb-96f3-0f16b5352d18.png)
![Snipaste_2021-02-28_20-54-14](https://user-images.githubusercontent.com/68289686/109419176-19e63400-79c4-11eb-9c6d-6045e6f30157.png)

**Comment by zcg** [comment]
in the first picture ，i also found task detekCheck failed，i dont know why

**Comment by vanniktech** [comment]
Build failed because detekt finds issues.
