### ISSUE TITLE
Plugin does not hook into build life cycle

### ISSUE THREAD

**Issue by johnhall** [vanniktech/gradle-code-quality-tools-plugin#24]
Added the plugin to my project and in the debug output it shows that Gradle finds it, downloads it and recognizes the plugin as an available tool in the project, but it doesn't automatically hook the plugin into the build life cycle. 

I configured it to the build.gradle as your readme instructed.  I'm running Java 8 and Gradle 2.12.

**Comment by vanniktech** [comment]
Well the plugin hooks into the `check` task. Do you execute this? Also a `build` should execute `check` which then executes `checkstyle`, `pmd` and all the alike.

Also could you post the output of `./gradlew tasks --all`?

**Comment by johnhall** [comment]
Sorry, I needed to get this done, so I just went with the plugins now
included with Gradle. I did run the 'check' task and the quality tasks
didn't run.  I also ran the 'tasks -all' before switching and didn't see
any tasks related to your plugin.


On Thu, May 5, 2016 at 2:23 PM Niklas Baudy <notifications@github.com>
wrote:

> Well the plugin hooks into the check task. Do you execute this? Also a
> build should execute check which then executes checkstyle, pmd and all
> the alike.
>
> Also could you post the output of ./gradlew tasks --all?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/vanniktech/gradle-code-quality-tools-plugin/issues/24#issuecomment-217267401>
>
-- 
John Hall
OJH Solutions, LLC
303.475.1397

**Comment by vanniktech** [comment]
Alright, so we can close this?!

**Comment by johnhall** [comment]
Yep. Sorry to bother you

On Fri, May 6, 2016 at 1:40 AM Niklas Baudy <notifications@github.com>
wrote:

> Alright, so we can close this?!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/vanniktech/gradle-code-quality-tools-plugin/issues/24#issuecomment-217371725>
>
-- 
John Hall
OJH Solutions, LLC
303.475.1397

**Comment by vanniktech** [comment]
No worries. If you'll try it again and encounter a new problem or the same just reopen or create a new one!
