### ISSUE TITLE
Unable to add multiple checkstyle inclusion/exclusion patterns

### ISSUE THREAD

**Issue by budnyjj** [vanniktech/gradle-code-quality-tools-plugin#67]
Hi @vanniktech, thanks for the great plugin! I believe it will become very popular soon.
There some issues, however, that prevent us from use it in production. Here is one of them.

We found that there is no way to setup more then on exclusion patter for checkstyle configuration, because checkstyle **exclude** setting has a string type:
https://github.com/vanniktech/gradle-code-quality-tools-plugin/blob/master/src/main/groovy/com/vanniktech/code/quality/tools/CodeQualityToolsPluginExtension.groovy#L96

IMHO it would be great to replace it with a array-like structure to configure it in more flexible way.

**Comment by vanniktech** [comment]
You said exclusion in the description however linked to `include`. Which one do you want? If one gets changed the other one should get changed too, the same also for the other configurations / extensions (PMD & Checkstyle.)

I'm open to changing it from `String` to `List<String>` or `String[]` as long as the Gradle Plugin supports this type (those values are passed down to the actual pmd, checkstyle & findbugs plugins provided by Gradle). However the default values should be kept.

**Comment by budnyjj** [comment]
We need to set multiple exclusion settings at least.
It would be great to customize inclusion in this way as well.

**Comment by vanniktech** [comment]
If one is done the other should not be a problem.

**Comment by budnyjj** [comment]
Implemented in my patchset https://github.com/vanniktech/gradle-code-quality-tools-plugin/pull/72 . @vanniktech , please, review it.

**Comment by vanniktech** [comment]
Fixed by #72
