### ISSUE TITLE
Create per-flavor findbugs tasks

### ISSUE THREAD

**Issue by budnyjj** [vanniktech/gradle-code-quality-tools-plugin#68]
It would be great to add per-flavor findbugs tasks to check only required classes
and don't depend on 'assemble' anymore, like it's done in:
https://github.com/ChaitanyaPramod/findbugs-android

Such measure should significantly decrease the build time.

**Comment by budnyjj** [comment]
See my patchset: https://github.com/vanniktech/gradle-code-quality-tools-plugin/pull/75

**Comment by vanniktech** [comment]
Closing this. Have a look at #75 for the reasoning behind this.
